### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by ajlanghorn** [goldyfruit/puppet-grub2#10]
Since https://github.com/goldyfruit/puppet-grub2/pull/7 was merged, the dependency on `puppetlabs/stdlib` has changed - this module now needs at least 4.6.0 since that is when the `validate_integer` function was introduced. I'll look at fixing this in `metadata.json` shortly.

**Comment by goldyfruit** [comment]
@ajlanghorn Should be fine, i used already a range:
```
 { "name": "puppetlabs/stdlib", "version_requirement": ">=3.2.0 <5.0.0" }
```

**Comment by ajlanghorn** [comment]
That's true, but I meant that the `metadata.json` file should possibly enforce the minimum required version, which would be 4.6.0. There's a PR for you to look at which does that, if you feel so inclined.

**Comment by goldyfruit** [comment]
:+1:
