### ISSUE TITLE
Remove duplication of GRUB_DISABLE_RECOVERY in `grub2` template

### ISSUE THREAD

**Issue by ajlanghorn** [goldyfruit/puppet-grub2#14]
In certain conditions, it's possible to end up with duplicate configuration options in `/etc/default/grub2`. Remove that chance by changing the logic in here: https://github.com/goldyfruit/puppet-grub2/blob/master/templates/default_grub.erb#L66

**Comment by goldyfruit** [comment]
@ajlanghorn Not a bad idea :+1:
