### ISSUE TITLE
Error in 50_password.erb

### ISSUE THREAD

**Issue by andreyhammer** [goldyfruit/puppet-grub2#23]
Hi!
Seems 50_password.erb have error:
 `exec tail -n +3 $0` must be on second line, after `#!/bin/sh`

**Comment by goldyfruit** [comment]
Thanks @andreyhammer 

I did the change: https://github.com/goldyfruit/puppet-grub2/commit/8ecd8fb2c35fe7f55d7c924294e9db9a3b4da1d1

Is it fixing your error ?

**Comment by andreyhammer** [comment]
Yes, now ok. Thank you!
