### ISSUE TITLE
version bump

### ISSUE THREAD

**Issue by flokli** [goldyfruit/puppet-grub2#27]
Hey,

awesome module, thanks!

Could you release a newer version of it to the Puppetforge?

I'd like to use the multi-device install features, but so far, this can only be found by pointing to git master…

**Comment by goldyfruit** [comment]
Hey @flokli !

I'll bumb a new version before the end of the wee.

Thanks.

**Comment by goldyfruit** [comment]
@flokli Bumped :)

**Comment by flokli** [comment]
Thanks :-)
