### ISSUE TITLE
install_grub only in case of changes

### ISSUE THREAD

**Issue by flokli** [goldyfruit/puppet-grub2#28]
Is there a possibility to install grub to the configured install devices only in case there are changes?

Currently, I have to toggle the `install_grub` parameter every time I want to write, as the bootloader will otherwise get written again and again on each puppet run, which might be bad for some disks (read: flash storage).

I'm not sure whether grub-install produces state files somewhere, but maybe this module could otherwise store information about which grub version is installed on which disk, and only perform the installation in case there is a new grub version or a new disk selected.

**Comment by goldyfruit** [comment]
@flokli I'll have a look on that.

**Comment by goldyfruit** [comment]
@flokli 
Could you please try to replace the code in ``install.pp``by this one:
```
# class: grub2::install: See README for documentation
class grub2::install inherits grub2 {

  $real_device_install = any2array($grub2::device_install)

  if $grub2::install_grub {
    package { $grub2::package_name:
      ensure => $grub2::package_ensure,
    }

    if !empty($real_device_install) {
      each($real_device_install) |$device| {
        exec { "Install GRUB on ${device}":
          command     => "${grub2::install_binary} ${device}",
          subscribe   => File[$grub2::config_file],
          refreshonly => true,
        }
      }
    }
  }

}
```
Not sure about the fix but I think to achieve what you need we have to split ``install.pp`` in two tasks:
  - Install the package
  - Install GRUB in the MBR only if configuration or package changed

**Comment by flokli** [comment]
Not sure if installing GRUB into the MBR depends on the grub config itself at all, I thought it only needs to be reinstalled in case of a package upgrade of grub itself (and during initial install).

**Comment by goldyfruit** [comment]
@flokli yes, you're right. Let's try this snippet:
```
# class: grub2::install: See README for documentation
class grub2::install inherits grub2 {

  $real_device_install = any2array($grub2::device_install)

  if $grub2::install_grub {
    package { $grub2::package_name:
      ensure => $grub2::package_ensure,
    }

    if !empty($real_device_install) {
      each($real_device_install) |$device| {
        exec { "Install GRUB on ${device}":
          command     => "${grub2::install_binary} ${device}",
          subscribe   => Package[$grub2::package_name],
          refreshonly => true,
        }
      }
    }
  }

}
```

**Comment by flokli** [comment]
My bad, of course puppet doesn't know if an exec resource was already defined on a previous run, and I'm uncomfortable with the idea of having puppet placing files somewhere to keep track of previous runs, or error-prone `dd`ing around with the block device.

So probably your last suggestion is fine, if a note is added to the README regarding initial installs (in case the grub package was installed before invoking puppet.
