### ISSUE TITLE
Symbolic link

### ISSUE THREAD

**Issue by linuxdan** [goldyfruit/puppet-grub2#4]
tar ztvf goldyfruit-grub2-0.0.1.tar.gz
...
lrwxrwxrwx root/root 0 2014-03-03 15:47 goldyfruit-grub2-0.0.1/spec/fixtures/modules/grub2 -> /srv/data/puppet/envs/production/modules/grub2
...

And it gripes
Error: No such file or directory - /etc/puppet/modules/grub2/spec/fixtures/modules/grub2
Error: Try 'puppet help module install' for usage

**Comment by goldyfruit** [comment]
@linuxdan Should be fixed now. Thanks
