### ISSUE TITLE
use of puppet 4 features

### ISSUE THREAD

**Issue by lelutin** [goldyfruit/puppet-grub2#43]
Salut!

Since I started using your module at my workplace, I'd like to work on making the module use a bit more of the puppet 4 syntax to make the code lighter to read and also more malleable for future changes, might there be some required. However, before actually working I'd just like to know how interested in this you are.

I'm thinking at least of
* using types in parameter definitions instead of using validate_*() from stdlib
* to replace the anchor pattern by the use of the "contain" keyword
** this would also let us drop use of inheritance for install, config, update

were you thinking of keeping support for an older version of puppet, 3.x or 2.7 ? or would you be willing to start moving towards code that's more in the puppet 4 realm?

Cheers!

**Comment by goldyfruit** [comment]
@lelutin I think it's time to move forward and make it compliant with Puppet 4 !
Thanks for your help.

**Comment by goldyfruit** [comment]
Two years later, I'm closing this issue with support for Puppet 6.

**Comment by lelutin** [comment]
:tada: :confetti_ball:  nice! thanks for the work
