### ISSUE TITLE
No tag/release for 1.0.8?

### ISSUE THREAD

**Issue by stdietrich** [goldyfruit/puppet-grub2#45]
Hello,

version 1.0.8 is available on Puppet Forge, however there is no corresponding git tag here on GitHub.
It would be great, if the git tag could be included in the repository.

Regards,
Stefan

**Comment by paescuj** [comment]
This would be really great! :smile:

**Comment by goldyfruit** [comment]
Sorry for the long delay... I'll create a tag after the next PR is merge.

**Comment by goldyfruit** [comment]
1.0.9 released.

**Comment by goldyfruit** [comment]
Published on the forge.

![image](https://user-images.githubusercontent.com/614115/103803550-b7556500-501e-11eb-9dd1-1f8f9cec1f71.png)
