### ISSUE TITLE
Update README about EFI

### ISSUE THREAD

**Issue by goldyfruit** [goldyfruit/puppet-grub2#53]
@Gurbmeister could you please update the `README` about the `EFI` support option you added?
Like, what type is `efi` option, how to use it, etc..

Thanks.

**Comment by Gurbmeister** [comment]
@goldyfruit PR is send

**Comment by goldyfruit** [comment]
https://github.com/goldyfruit/puppet-grub2/pull/54

**Comment by goldyfruit** [comment]
Thanks, merged!
