### ISSUE TITLE
Add GRUB_TIMEOUT_STYLE

### ISSUE THREAD

**Issue by enkidushane** [goldyfruit/puppet-grub2#82]
The module doesn't currently have a way to set GRUB_TIMEOUT_STYLE, which is now preferred over the deprecated GRUB_HIDDEN_TIMEOUT and GRUB_HIDDEN_TIMEOUT_QUIET settings.
(According to https://www.gnu.org/software/grub/manual/grub/html_node/Simple-configuration.html)

I'm working on an initial PR that adds this functionality, sets new default, and tries to do the right thing if the deprecated values are explicitly set when calling the class.

**Comment by goldyfruit** [comment]
Thanks @enkidushane

**Comment by goldyfruit** [comment]
Released and published on Puppet Forge.
