### ISSUE TITLE
Mismatched brackets in latest update init.pp

### ISSUE THREAD

**Issue by rubilab** [goldyfruit/puppet-grub2#84]
The latest tag has introduced errors due to mismatched brackets.
 
Syntax error at ')' (file: modules/grub2/manifests/init.pp, line: 237, column: 101)

Thanks!

**Comment by goldyfruit** [comment]
@rubilab Thanks for pointing tihs, I just pushed a commit, could you please tell me if it fixes the issue introduced in #82

**Comment by rubilab** [comment]
Hi @goldyfruit yes, the commit has fixed the problem. Thanks!

**Comment by goldyfruit** [comment]
Released and published, thanks again!

**Comment by rubilab** [comment]
@goldyfruit It looks like the changes are not reflected in [puppet forge]( https://forge.puppetlabs.com/modules/goldyfruit/grub2). If I do a direct download of the module from forge, the code is different from the code in 1.0.13 in github. Do you know why?

**Comment by goldyfruit** [comment]
@rubilab I don't. I just uploaded a new version on the forge, let me know.

**Comment by rubilab** [comment]
Thanks @goldyfruit It works now
