### ISSUE TITLE
RHEL 8 + Puppet 7.18 never exports superusers

### ISSUE THREAD

**Issue by njdtroubleshoot** [goldyfruit/puppet-grub2#85]
The `/etc/grub.d/50_password` file gets setup and included in the file `/boot/grub2/grub.cfg` just fine.

But the only place that calls logic to actually export the defined superusers is in `/etc/grub.d/01_users` as follows:

`#!/bin/sh -e
cat << EOF
if [ -f \${prefix}/user.cfg ]; then
  source \${prefix}/user.cfg
  if [ -n "\${GRUB2_PASSWORD}" ]; then
    set superusers="root"
    export superusers
    password_pbkdf2 root \${GRUB2_PASSWORD}
  fi
fi
EOF`

This module doesn't do its work in 01_users however so that code block never gets touched and you end up with a /boot/grub2/grub.cfg that contains a superuser definition and its hashed password but `export superusers` is never called so no password is ever required.

I tested and fixed by fudging in `export superusers` to the end of the `/etc/grub.d/50_password` file that the module generates.  This module needs to include that export command to achieve its stated effect.

**Comment by njdtroubleshoot** [comment]
I worked around more permanently but updating the 50_password.erb in the templates folder

**Comment by goldyfruit** [comment]
@njdtroubleshoot could you please send a PR with your workaound?

**Comment by njdtroubleshoot** [comment]
My workaround actually was not repeatable. I had ran the grub2-mkconfig manually and confounded my results.  I don't have a fix.  Maybe I'm using the module wrong but its still not working for me.  I end up with user and pass in the 50_password file but it never reaches the final grub config.  executing puppet with -v does show the module triggering a rebuild of the file so I'm at a loss.

**Comment by goldyfruit** [comment]
Ok, I'll close then. Thanks for letting me know. :+1:
